[package]
name = "aichdl"
version = "0.4.0"

[package.edition]
workspace = true


[package.license]
workspace = true


[package.authors]
workspace = true


[dependencies.reqwest]
workspace = true

[dependencies.tokio]
workspace = true
features = ["io-util", "rt"]

[dependencies.scraper]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.serde]
workspace = true
features = ["derive"]

[dependencies.toml]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.tracing-subscriber]
workspace = true

[dependencies.tracing-appender]
workspace = true



[[bin]]
name = "MCP_zhihu"
path = "src/main.rs"